apiVersion: v1
kind: Secret
metadata:
  name: aws-s3-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: YOUR_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: YOUR_SECRET_ACCESS_KEY
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET_NAME: your-bucket-name

